apiVersion: apps/v1
kind: Deployment
metadata:
  name: ps
  labels:
    app: ps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ps
  template:
    metadata:
      labels:
        app: ps
    spec:
      containers:
      - name: ps
        image: kelseybowen/personal-site
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: secret-volume
          mountPath: /etc/secret-volume
          readOnly: true
        env:
        - name: SSL_CRT_FILE
          value: /etc/secret-volume/tls.crt
        - name: SSL_KEY_FILE
          value: /etc/secret-volume/tls.key
        - name: HTTPS
          value: "true"
      volumes:
      - name: secret-volume
        secret:
          secretName: wildcard-cert